version: '3.9'

services:
  GameZone:
    image: node:latest
    container_name: GameZone
    working_dir: /app
    volumes:
      - .:/app
      - GameZone_node_modules:/app/node_modules  # Separate node_modules volume
    ports:
      - "8081:8081"     # Metro
      - "19000:19000"   # Expo Go main port
      - "19001:19001"   # Expo Go WebSocket
      - "19002:19002"   # Expo Dev Tools
    environment:
      - CHOKIDAR_USEPOLLING=true
      - EXPO_USE_POLLING=true
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.100.35
    stdin_open: true
    tty: true

volumes:
  GameZone_node_modules:
